### ISSUE TITLE
Проблемы с запуском

### ISSUE THREAD

**Issue by keipa** [sergey-brutsky/onliner-prices-watcher#1]
Столкнулся с Bad Request при запуске твоей прилаги. Как я понял -  часть апишки переехало на новый адрес. Я попробовал потыкать в другую. Но ничего не вышло. Можешь посоветовать что-нибудь?

**Comment by sergey-brutsky** [comment]
Дело в том что app пока не доделан, я пока занимаюсь другими проектами.
Как вернусь и запущу рабочий прототип, я тебе сообщу

**Comment by keipa** [comment]
спасибо, буду ждать 👍
